name: Progress Heatmap

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
  schedule:
    - cron: "17 3 * * *"   # daily

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate dashboards
        env:
          TARGET_DIRS: "CSES,USACO,atcoder,codechef,codeforces"
          # last 12 months for the heatmap (dashboard shows “year” + “month” + all time stats)
          WINDOW_DAYS: "365"
          TZ_REGION: "Europe/Berlin"

          # outputs (SVG for README, JSON for debugging, interactive HTML page)
          OUTPUT_SVG_YEAR: ".github/.assets/heatmap_year.svg"
          OUTPUT_DASHBOARD: ".github/.assets/progress_dashboard.svg"
          OUTPUT_JSON: ".github/.assets/heatmap_data.json"
          OUTPUT_HTML: ".github/.assets/docs/progress.html"

          # restrict counted files (comma-separated, leave empty for all)
          ALLOWED_EXTS: ".cpp"
        run: |
          python3 .github/.assets/scripts/generate_heatmap.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add .github/.assets/heatmap_year.svg .github/.assets/progress_dashboard.svg .github/.assets/heatmap_data.json .github/.assets//docs/progress.html || true
          git diff --cached --quiet || git commit -m "chore: update CP progress dashboard [skip ci]"
          git push
